include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    non_constant_identifier_names: false
    omit_local_variable_types: false
    curly_braces_in_flow_control_structures: false
    avoid_print: false
    library_private_types_in_public_api: false
